name: post
on :
  push :
    branches:
      - main
jobs:
  build-deploy:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name : build
        run : |
          docker build -t dev19med/counter-app .
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
          docker push dev19med/counter-app

