name: pipeline


on:
    push:
        branches:
            - main


jobs:
    build-image:
     runs-on: ubuntu 
     name: build
     steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
     
